### ISSUE TITLE
Stuck at the pool

### ISSUE THREAD

**Issue by Bamarin** [syl0r/Perpheads-Issues#31] opened 2015-01-21 08:54 UTC
I've noticed that you can no more jump out the water at docks and the pool in subs1 and now you just have to run to an edge of the pool. but it makes almost impossible to exit the pool at city hall and bazaar since the water level is too low 

The only wa you can exit the Cit Hall pool is staying crouch and walk to the side of the pool
The only wa you can exit the bazaar pool is staying under the bridge and jumping untill you will get over it due to another bug

**Comment by StephenPuffs** [comment] 2015-01-27 06:29
Anti stuck is not a bug, it is a feature to help anyone out that happens to get into locations in which they can not move.  Unlike other servers which this requires an admin to respond.  However I will check out allowing people to jump while in water.

**Comment by StephenPuffs** [comment] 2015-02-02 13:33
This should be fixed or I somehow magically can jump out of the bazaar pond just fine.  Tbh not sure if I released this already or not, if not please wait patiently for release.

**Closed by StephenPuffs** 2015-02-02 13:33 UTC
Labels: minor
