### ISSUE TITLE
Phone sometimes gets stuck on emergency app

### ISSUE THREAD

**Issue by affgaming** [syl0r/Perpheads-Issues#18] opened 2015-01-03 01:01 UTC
As the title describes, may be the case with other apps too.

**Comment by phshaun** [comment] 2015-01-03 03:12
This is a known issue.

**Comment by StephenPuffs** [comment] 2015-01-04 12:47
@affgaming Can you be more specific please?  As in what were you doing at that time that may have had an adverse effect to the functioning of your phone.  (Such as dying, closing the phone a few times while on the 911 app, etc)  Or if you can recall all actions you took with your phone until that point.  We have never been able to exactly isolate the cause of this problem as we can't reproduce it, so as much detail as possible would be helpful.

**Comment by Bamarin** [comment] 2015-01-04 22:34
I had this bug too a long time ago, it's rare but sometimes if you send a message with the 911 app and then you close your phone, when you re-open it you can't move out from the 911 app

**Comment by JDaymon** [comment] 2015-01-05 01:09
For me it get stuck after 10 min of not touching the phone, i took time a day and tested it. Took me exactly 10 min to get it stuck both times

**Comment by GabrielRoss2** [comment] 2015-01-05 18:02
it happend to me when i had the emergency app open and the went and got a job

**Comment by BenStandish** [comment] 2015-01-06 20:24
This has happened for a LONG time, like since V1. The phone (if left) will just stay on a menu you left it on some time ago, as Daymon said, possibly 10 minutes. You can't exit to the homepage either.

**Comment by StephenPuffs** [comment] 2015-01-07 06:49
Yes we know it has been occurring for quite some time, but the problem is we never could reproduce it so trying to understand what may be the cause of it has not been possible.  I will check the 10 minute wait as well as joining a job with it open, as they are our only leads so far.

**Comment by Bajar** [comment] 2015-01-17 19:56
if you have your phone on a tab and you die or get a job your phone will stay on that tab until you relog .

**Comment by syl0r** [comment] 2015-01-18 01:44
Bajar I tested both scenarios and both worked for me.

**Comment by moher4** [comment] 2015-01-21 13:29
i noticed that the phone always get stuck in the dialer app or the 911 app if you use any of them and close your phone without exiting the apps its ether that or it is leaving the app open then someone calling your phone that gets it bugged

**Comment by Bamarin** [comment] 2015-01-22 18:34
tbh if i now click on the HOME button it closes the app which was open, so i guess it's fixed now

**Comment by JDaymon** [comment] 2015-01-27 07:40
Tested this yesterday, got stuck after changing job

**Comment by JDaymon** [comment] 2015-01-30 18:41
I got the answer, me and Creepis were testing this out today. Basically when you get handcuffed and have any app up and unhandcuffed it will get stuck. Need of a demo? Just ask!

**Comment by syl0r** [comment] 2015-02-02 08:21
Fixed.

**Closed by syl0r** 2015-02-02 08:21 UTC
Labels: can't reproduce, minor
