### ISSUE TITLE
Able to fly on large wood fences

### ISSUE THREAD

**Issue by KeiwaM** [syl0r/Perpheads-Issues#274] opened 2016-06-08 16:09 UTC
A While back when I tried to make a base with wooden boards, one of them fell down. I Accidentally stood on it and lifted it in the other corner. From here I was able to lift myself on the wooden fence. I Reckon I could've lifted myself well up to the map's height-limit but I obviously didn't do that.

It's simply done by Standin on the edge of one corner and using a physgun on the other corner. Not many people know that you can do it luckily.

**Comment by LaCreepis** [comment] 2016-06-09 14:40
This is literally just Garry's Mod and how you can prop surf thanks to the Physics Gun, this is possible with any prop, hell even hamburger's. There wouldn't be any fix for this but it's obviously punishable.

**Comment by LEWIS088** [comment] 2016-06-09 14:40
Lmao not a bug...

**Closed** 2016-06-22 15:47 UTC
