### ISSUE TITLE
Limousine not spawning for SS

### ISSUE THREAD

**Issue by GarretPp** [syl0r/Perpheads-Issues#383] opened 2016-10-13 16:00 UTC
A player reported to me today that the Limousine will not spawn when SS attempt to.

**Comment by PHSneaky** [comment] 2016-10-16 18:12
duplicate of https://github.com/syl0r/Perpheads-Issues/issues/375

**Comment by LaCreepis** [comment] 2016-10-20 15:39
Limousine has been fixed and is spawnable again.

**Closed** 2016-11-16 09:31 UTC
